In [41]:
import pandas as pd

# Задание 1

In [45]:
import json
purchases = {}
i = 1

with open("purchase_log.txt", "r", encoding="cp1251") as file:
    file.__next__()
    a = file.readlines()

for element in a:
    element_js = json.loads(element)
    value = element_js["category"]
    key = element_js["user_id"]
    purchases.update({key : value})
 
for key, value in purchases.items():
    if i == 3: 
        break
    print(key, value)
    i += 1

1840e0b9d4 Продукты
4e4f90fcfb Электроника

In [46]:
pd.DataFrame.from_dict(purchases, orient='index').head()

                          0
1840e0b9d4         Продукты
4e4f90fcfb      Электроника
afea8d72fc      Электроника
373a6055fe  Бытовая техника
9b2ab046f3      Электроника

# Задание 2

In [37]:
with open("funnel.csv", "w", encoding="cp1251") as end_file, open("visit_log (2).csv", "r", encoding="cp1251") as file_2:
        end_file.write(f"{file_2.readline().replace("\n", "")},category\n")
        file_2.__next__() 
        for line in file_2:
            if line.split(",")[0] in purchases.keys():
                end_file.write(f"{line.replace("\n", "")},{purchases[line.split(",")[0]]}\n")

In [40]:

funnel = pd.read_csv('funnel.csv', sep = ',', encoding="cp1251")
funnel.head()

      user_id   source         category
0  1840e0b9d4    other         Продукты
1  4e4f90fcfb  context      Электроника
2  afea8d72fc    other      Электроника
3  2824221f38    email         Продукты
4  373a6055fe    other  Бытовая техника